name: 'Check if all checks passed'
description: 'same as name'
author: 'P'

inputs:
  myInput:
    description: "Input to use"
    default: "default input"

outputs:
  myOutput:
    description: "Output from the action"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "green"
