name: testing autoapprove

on:
  check_suite:
    types: 
      - completed
  pull_request:
    branches:
      - master
    types:
      - labeled

jobs:
  merge_automated_PR:
    
    if: contains(github.event.pull_request.labels.*.name, 'automated_pr')

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Validate Release
      uses: xembly/validate-workflow-status@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Github Actions, you do not need to create your own token
        workflow: A workflow for my Hello World file
        branch: master    #optional
        status: success  # optional

    - name: Auto approve
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
