name: Merge automated PR to branch development

on:
  pull_request:
    branches:
      - master
    types:
      - labeled

jobs:
  merge_automated_PR:
    if: contains(github.event.pull_request.labels.*.name, 'automated_pr')

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Wait for Hello
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-Terraform
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: Hello world action
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: automerge
      if: steps.wait-for-Terraform.outputs.conclusion == 'success'
      uses: "pascalgn/automerge-action@v0.12.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "automated_pr"
        MERGE_DELETE_BRANCH: "true"
