name: Merge automated PR

on:
  status

jobs:
  merge_automated_PR:

# Czy status jes succes??
    if: contains(github.event.status.state.*.name, 'success')

# Jeśli status success szukamy PR
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Debug
      run: echo $EVT
      env:
        EVT: ${{ toJSON(github.event.status) }}
