name: testing autoapprove

on:
  check_suite:
    types: 
      - completed
  pull_request:
    branches:
      - master
    types:
      - labeled

jobs:
  merge_automated_PR:
    name: success-check
    if: contains(github.event.pull_request.labels.*.name, 'automated_pr')

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Check
      uses: arup-group/action-all-checks-passed@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto approve
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
