name: My test action

on:
  push

jobs:
  my_test_action :

#    if: contains(github.event.status.state.*.name, 'success')

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2 # checkout the repository content to github runner

    - name: setup python
      uses: actions/setup-python@v2

    - name: execute py script # run the run.py
      run: |
        run: echo $COMMIT_SHA
        run: echo $GITHUB_TOKEN
        pip install PyGithub
        python scripts/run.py
      env:
        COMMIT_SHA: ${{ github.event.push.commits.sha }} 
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
